Jenkinsfile-deploy

AWS container upgraded to python 3
Upating Jenkins script to reference python 3

Upgrade to python 3

---

Jenkinsfile-testing

This should fix the master build.

Add missing versionTag variable to Jenkinsfile

---

Jenkinsfile-deploy

Add text formatting and emoji to make the messages clearer. :whale:

Update wording of Jenkins Slack messages

---

Jenkinsfile-deploy
Jenkinsfile-testing

Some more tweaks to make the messages clearer and update the Slack channel.

Reword the deployment Slack messages

---

build.sbt
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/ConsignmentApiContext.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/Tags.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/Routes.scala

Ignore the branch name, I had a brain fail.

Update api to use new auth utils

---

build.sbt

Error in jar where "akka" key was found to be missing from configuration
See stack overflow: https://stackoverflow.com/questions/28365000/no-configuration-setting-found-for-key-akka

Added different merge stategy for conf

---

Dockerfile
src/main/resources/application.base.conf
src/main/resources/application.conf
src/main/resources/application.intg.conf
src/main/resources/application.prod.conf
src/main/resources/application.staging.conf

This will make it easier to add different CORS configuration to integration vs staging and production.
It will also make it easier to set up a development environment, because the local database connection config is in the dev-specific config file.
https://national-archives.atlassian.net/browse/TDR-113

Split config into environment-specific files

---

build.sbt
src/main/resources/logback.xml
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/SeriesRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala

Configure API to log everything at info level and above to STDOUT.
This fixes the issue with almost nothing being logged to Cloudwatch.

Update logging configuration

---

Dockerfile

I've tested this locally with java 16 and it works fine.

Move the image to use alpine.

---

src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/FixedUUIDSource.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/RandomUUIDSource.scala

- Add new case class for the new static metadata.
- Add static metadata when the files are added.
- Add file metadata repository to file service object
- Update existing tests and add new ones.

Add static metadata

---

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/DeferredResolver.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FieldTypes.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
src/test/resources/json/getconsignment_data_file_metadata.json
src/test/resources/json/getconsignment_query_filemetadata.json
src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepositorySpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala

- Add a LocalDateTime scalar type
- Add service and repository methods to get metadata.
- Add service and repository tests
- Add deferred fields to consignment object.

Add metadata field to consignment object

---

Jenkinsfile-testing
README.md
build.sbt
schema.graphql

I've added in a `schema.graphql` file which shows the current API schema and an sbt task called compareSchema.
This will run graphqlSchemaGen and compare the output with the file in `schema.graphql`. If they don't match, then the test build will fail. I've updated the README to include instructions on what to do.

Add graphql schema file and check

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/consignmentstatevalidation/ConsignmentStateTags.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentStatusRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala
src/test/resources/json/startupload_mutation_alldata.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala

- Add startUpload mutation.
- Add a test for the new service method

Create start upload mutation

---

src/main/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataService.scala

If av match found add this to logging message to help with debugging issues
At the moment need to log on to Bastion to access DB to find what av match has been found

Add av match result to logging

---

src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentStatusRepositorySpec.scala

Fix some failing tests due to rounding of time on windows machines

Fix test failing due to time difference between linux and windows

---

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala
src/test/resources/json/addffidmetadata_mutation_status_judgment_multiple_success.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FFIDMetadataRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataServiceSpec.scala

Change puid allow list for judgment to only include docx puid

Only allow docx formats for judgments

---

build.sbt
src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/Routes.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/RoutesSpec.scala

There is a vulnerability in the old one. The two changes I've made to
the code were only deprecations but it's good to keep things up to date.

Upgrade akka http

---

.gitignore
schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentStatusFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusService.scala
src/test/resources/json/updateconsignmentstatus_data_all.json
src/test/resources/json/updateconsignmentstatus_data_invalid_statustype.json
src/test/resources/json/updateconsignmentstatus_data_invalid_statustype_and_statusvalue.json
src/test/resources/json/updateconsignmentstatus_data_invalid_statusvalue.json
src/test/resources/json/updateconsignmentstatus_mutation_data_all.json
src/test/resources/json/updateconsignmentstatus_mutation_invalid_consignmentid.json
src/test/resources/json/updateconsignmentstatus_mutation_invalid_statustype.json
src/test/resources/json/updateconsignmentstatus_mutation_invalid_statustype_and_statusvalue.json
src/test/resources/json/updateconsignmentstatus_mutation_invalid_statusvalue.json
src/test/resources/json/updateconsignmentstatus_mutation_not_owner.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentStatusRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusServiceSpec.scala

...by making it an 'updateConsignmentStatus' method.

Make 'setUploadConsignmentStatusValueToComplete' more generic

---

.github/workflows/test.yml
build.sbt
src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepositorySpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestContainerUtils.scala

This runs one database docker container per test which is quite slow so now we're running them in parallel

One container per test

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepositorySpec.scala

Add file filters in consignment's 'files' field to query the files only for given file Ids

Update consignment query

---

build.sbt
schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/CustomMetadataFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesService.scala
src/test/resources/json/custommetadata_data_all.json
src/test/resources/json/custommetadata_query_alldata.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/CustomMetadataRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala

Add ordinal to API query
This is the ordinal on file property values

TDR 2298 add ordinal to api query

---

src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusService.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusServiceSpec.scala

As part of the backend checks changes, I'm adding in the consignment
statuses to show the backend checks as in progress.

Add new consignment statuses.

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusService.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusServiceSpec.scala

Additional statuses required to support 'view transfer' feature

Add further consigment statuses

---

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileStatusService.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileStatusServiceSpec.scala

Return ClosureMetadata and DescriptiveMetadata file statuses too

TDR-2755 - Return all file statuses

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala
src/test/resources/json/consignments_data_current_page.json
src/test/resources/json/consignments_query_with_current_page.json
src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala

Add `currentPage` argument in the consignments query for pagination on the view transfer page

TDR-2854 - Pagination on the view transfer page

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FinalTransferConfirmationFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FinalTransferConfirmationService.scala
src/test/resources/json/addfinaljudgmenttransferconfirmation_mutation_alldata.json
src/test/resources/json/addfinaljudgmenttransferconfirmation_mutation_invalid_consignmentid.json
src/test/resources/json/addfinaljudgmenttransferconfirmation_mutation_missingconsignmentid.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FinalTransferConfirmationRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FinalTransferConfirmationServiceSpec.scala

[TDR-2078](https://national-archives.atlassian.net/browse/TDR-2078?atlOrigin=eyJpIjoiMDcyNGRiODVjMDFiNGM3NTgzNzJmNDhjMTQyNjNhZGIiLCJwIjoiaiJ9)
[TDR-2078]: https://national-archives.atlassian.net/browse/TDR-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TDR-2078 Migrate addFinalTransferConfirmation

---

src/main/resources/logback.xml
src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala

also disable sql statement logging

Enable cats thread blocking detection

---

src/main/scala/uk/gov/nationalarchives/tdr/api/db/DbConnectionHttp4s.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServerHttp4s.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/http/Http4sServer.scala

I've changed this so we're passing in a Hikari data source and the
Database object is created from that.
I'm not 100% sure why this is working but it seems to be.

Pass in data source.

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FFIDMetadataFields.scala

[TDR 3367](https://national-archives.atlassian.net/browse/TDR-3367?atlOrigin=eyJpIjoiZDgzMGQwNjAzYjhhNDMxZmE4MzQ4YjQ3ZGUyYTY3NTQiLCJwIjoiaiJ9)

Feat : updated case class & graphQL schema

---

Dockerfile

Download rds certificate bundle from here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions

TDR-3504 update rds certificate

---

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala
src/test/resources/application.conf
src/test/resources/json/getconsignment_data_all.json
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala

To be included in the bagit export

TDR-3690 Add File UUID to the filemetadata table

---

src/main/resources/application.base.conf
src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServerBase.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataService.scala
src/test/resources/application.conf
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataServiceSpec.scala

Remove old code to validate metadata and remove feature access block for validation library

TDR-3680 - Remove old code to validate metadata

---

.git-blame-ignore-revs
.scalafmt.conf
build.sbt
project/build.properties
project/plugins.sbt

Compilation of outstanding scala-steward PRs

Scala steward dependencies

---

schema.graphql
src/main/scala/uk/gov/nationalarchives/tdr/api/auth/AuthorisationTags.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala
src/main/scala/uk/gov/nationalarchives/tdr/api/utils/Statuses.scala
src/test/resources/json/getconsignmentsformetadatareview_data_all.json
src/test/resources/json/getconsignmentsformetadatareview_query_alldata.json
src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestAuthUtils.scala

A new query for fetching all consignments that have `DtaReview` status `InProgress`. Query can only be called by `TNAUser` type.

Add new `getConsignmentsForReview` query

---

src/main/resources/application.staging.conf

works fine on intg without this

TDRD-370: remove extra timeout on staging

---

.github/workflows/build.yml

Wiz secrets should already be defined at the organisation level

Pass wiz variables to ecs_build.yml
