nationalarchives/tdr-consignment-api

Jenkinsfile-deploy, Jenkinsfile-testing
Update the Jenkinsfiles to handle deployments in the same way as the frontend app:
- When code is merged to master, the Jenkins test build tags the current commit with a version tag, builds the Docker image and pushes it to Docker hub with the same version tag
- When a deployment build is run, Jenkins re-tags the Docker image with the environment name, deploys it to ECS and updates the release branch tag
- The master branch build triggers a deployment to integration if the build succeeds
=> Tag versions and releases in git, and use them for Docker deployments

build.sbt
sbt assembly merge strategy changed to prevent duplicated dependencies which cause assembly to fail
=> Change merge strategy to prevent duplicates

src/main/resources/application.conf
Allow developers to override the default database port with an environment variable. Some developers are running MySQL natively for another project, so they might want to run MySQL in Docker on a non-default port.
=> Parameterise database port

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/Tags.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/TransferAgreementFields.scala
I merged the changes to create the getTransferAgreement query on the api
and left the type checking using a Try and then assuming a Long value if
there was an exception.
It turns out that there is a better way and you can use the type on the
argument.
=> Changes to the type checking.

README.md, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/TimeSource.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/FixedTimeSource.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
The user's ID is used for auditing purposes, so we should read it from the user's authentication token rather than trusting the UUID sent by the client.
For now, make the user ID parameter in the GraphQL request optional, so that this change is backwards-compatible with the frontend client. The frontend will be updated to remove the parameter, and then the parameter can be removed from the API.
=> Get consignment creator from token

src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
The line here was comparing UUID and string types, I've added toString
so the test passes.
=> Fix the tests

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/ErrorCodes.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/test/resources/json/addfile_data_error_not_owner.json, src/test/resources/json/addseries_data_error_incorrect_role.json, src/test/resources/json/addtransferagreement_data_error_not_owner.json, src/test/resources/json/getseries_data_error_incorrect_user.json, src/test/resources/json/getseries_data_error_no_body.json, src/test/resources/json/getseries_data_incorrect_body.json, src/test/resources/json/gettransferagreement_data_notowner.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/SeriesRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/TransfersAgreementRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
GraphQL supports error codes to provide more information to the client applications. We can look for these code Strings in the GraphQL clients to provide better errors to the user.
For now, the only specialised error is NOT_AUTHORISED, which indicates that the request tried to do something which the user does not have permission for.
=> Add error code to GraphQL errors

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/test/resources/json/addconsignment_mutation_alldata.json, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
In a previous commit, we switched to getting the user ID from the auth token, so it is no longer needed in the GraphQL query.
PR marked as draft until https://github.com/nationalarchives/tdr-transfer-frontend/pull/58 is merged.
Edit: I found an issue in the graphql client that needs to be fixed first too: https://github.com/nationalarchives/tdr-graphql-client/pull/2
=> Remove user from consignment creation query

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/SeriesRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/Tags.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/SeriesFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/SeriesService.scala, src/test/resources/json/getseries_data_error_no_body.json, src/test/resources/json/getseries_data_multipleseries.json, src/test/resources/json/getseries_query_admin.json, src/test/resources/json/getseries_query_no_body.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/RouteAuthenticationSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/SeriesRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/SeriesServiceSpec.scala
This fixes an authorisation issue, where it was possible to fetch series for all departments by passing a null body parameter.
The only reason that body was an optional parameter was to support future admin functionality, but that does not exist yet so it's more secure to make the parameter compulsory are revisit this once we have requirements for the admin functions.
Also remove the admin token handling the same endpoint for the same reason.
Set as draft for now. The frontend needs to be updated to use https://github.com/nationalarchives/tdr-generated-graphql/pull/11 before this can be safely merged.
=> Make transferring body a compulsory argument when fetching series

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/SeriesRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/GraphQlTypes.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/SeriesFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/SeriesService.scala, src/test/resources/json/addseries_data_all.json, src/test/resources/json/addseries_data_error_incorrect_role.json, src/test/resources/json/addseries_data_some.json, src/test/resources/json/addseries_mutation_alldata.json, src/test/resources/json/addseries_mutation_somedata.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/SeriesRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/SeriesServiceSpec.scala
This mutation is not used by any of the clients, and it depends on a tdr_admin user which needs to be thought through further before we add any admin functionality.
=> Remove addSeries mutation

src/main/resources/application.base.conf, src/main/resources/application.conf, src/main/resources/application.intg.conf, src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/Cors.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/Routes.scala, src/test/resources/application.conf, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/CorsSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/RouteAuthenticationSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestRequest.scala
Configure frontend domains as a list rather than as a single value.
Use this to allow cross-origin requests to the integration API from the integration frontend AND the local dev environment.
This makes it possible to do local frontend development without setting up the rest of the TDR stack.
I haven't fully tested this locally because of the [current issues with local dev](https://national-archives.atlassian.net/browse/TDR-111). I have checked that the MVC site can still make requests to the API. If there are any issues, they'll be with JavaScript requests, but that might be easier to spot when it's deployed to integration.
=> Allow cross-origin requests from localhost to integration

src/main/resources/application.intg.conf
Add missing "http" scheme to localhost cross-origin domain.
=> Fix cross-origin domain in integration

build.sbt, project/build.properties
Upgrade to the latest versions of Scala and SBT.
This fixes a compiler error on my dev machine that I can't work out the cause of:
```
java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
```
=> Upgrade Scala and SBT

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/AntivirusMetadataFields.scala, src/test/resources/json/addavmetadata_data_datetime_missing.json, src/test/resources/json/addavmetadata_mutation_missingdatetime.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/AntivirusMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataServiceSpec.scala
The antivirus scan generates data for all of these fields, so they shouldn't be optional. Upgrade to the latest version of the generated database classes, which makes the fields mandatory in the database, and also make them mandatory in the GraphQL schema.
The only exception to this is the 'value' field, which is not used and will be deleted in a later commit.
=> Make antivirus metadata fields non-optional

Jenkinsfile-testing
There is no need to specify an agent for the post-build steps because it is the same as the pipeline's default agent. Re-specifying the agent only leads to deadlocks because the build tries to wait for another node to become available. If two builds are running at the same time, they are using all the available nodes already, so they get stuck.
=> Remove Jenkins post-build agent to fix Jenkins deadlocks

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataService.scala, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataServiceSpec.scala
This column is [about to be removed from the database](https://github.com/nationalarchives/tdr-consignment-api-data/pull/32), so update the consignment-api-db dependency, which removes it from the database classes.
Also remove the column from the test database. The tests pass before and after this change.
=> Upgrade generated DB classes to remove 'value' from antivirus metadata

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/DeferredResolver.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
Refactor the Consignment model so that the ID is compulsory. It's not clear why this was an Option in the first place, but removing it makes the code simpler because the deferred resolvers don't need to decide what to do if the value is None.
=> Make ID non-optional in the Consignment domain model

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/http/Routes.scala
Each time we were getting a token, we were creating a keycloak
deployment which contacts the keycloak server to get the oidc
configuration. This is a waste so the auth utils library has been
changed to take an implicit KeycloakConfiguration object. This means
that the config it only got once.
=> Pass keycloak deployment to auth utils

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FileFields.scala, src/test/resources/json/addfile_mutation_alldata.json, src/test/resources/json/addfile_mutation_one_file.json, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
These changes refactor the functions saving the parent folder name to the consignment table. Now that the front end is reliably saving the parent folder, it can be a `String` rather than `Option[String]`. I also amended some tests to reflect this change.
=> Refactor saving parent folder

src/main/scala/uk/gov/nationalarchives/tdr/api/service/TransferAgreementService.scala
Before removing the allDigital field from the API safely need to remove it from Transfer Agreement complete check
If not removed when allDigital field not passed in check fails and user is not redirected to the upload page
=> Remove allDigital field from agreement complete check

src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ClientFileMetadataRouteSpec.scala
This table no longer exists in the real DB, and the code does not depend on it, so it's safe to remove from the test database setup.
=> Delete references to ClientFileMetadata table from tests

src/test/resources/json/getconsignment_data_all.json, src/test/resources/json/getseries_data_all.json, src/test/resources/json/getseries_data_some.json, src/test/resources/json/getseries_query_alldata.json, src/test/resources/json/getseries_query_somedata.json, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentMetadataRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FFIDMetadataRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/AntivirusMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ClientFileMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FFIDMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/SeriesRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/TransfersAgreementRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestDatabase.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
This fixes an issue where some tests would fail if only a subset of the tests were run, because of inter-dependencies. Now you can run all of the tests, or just one folder, or just one individual test.
This is quite a large change because every time I fixed a test, a different one would fail. It took a while to unpick all of the interdependencies.
Part of the problem was that init.sql gets run at unexpected times. It looks like it just gets executed at the start of the test suite, but it actually gets run every time the code creates a new database connection! Hopefully that will be a moot point once we can [move to a more realistic test database](https://national-archives.atlassian.net/browse/TDR-150), but I've mitigated the problems in the meantime by moving all the static data creation …
=> Clean up test data after every test

src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala
Merge the `ALTER TABLE` statements with the `CREATE TABLE` statements rather than keeping them separate. This means the foreign keys are only added if the tables don't already exist.
This solves a `ConcurrentModificationException` problem that was causing the tests to fail intermittently. init.sql is run every time a new database connection is opened, because it's specified as an init script in the H2 configuration in the tests' application.conf. If multiple connections were opened in parallel, for example because Sangria was resolving deferred resolvers in parallel, this sometimes meant that data was being read by one thread while another thread ran `ALTER TABLE` on the same table.
This change should mean that init.sql never modifies existing tables, which should fix the concurrency …
=> Fix flaky tests

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FieldTypes.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/test/resources/json/getconsignment_data_all.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
To ensure clients can decode date times from API without custom decoders use ZonedDateTime for output
ZonedDateTime make the UTC timezone explicit to clients that need to use date times
=> Convert sql timestamp to ZonedDateTime

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FieldTypes.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/utils/TimeUtils.scala, src/test/resources/json/updateexportlocation_mutation_all.json, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
Export datetime value is required before the DB table is updated, so client provides this value.
=> Pass in export datetime instead of generating value

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestDatabase.scala
Due to the production and test DB's being different types of database, the consignment sequence object needed it's name changed to follow PostgreSQL convention.
The previous casing of the sequence ("ConsignmentSequenceId") meant that the sql query needed specific quotation marks to override the fact that tables/objects/columns are usually in lower snake case within PostgreSQL DB's, but these meant that the H2 database detected the sql different, meaning either the production API worked OR the tests passed. 
This change will hopefully lead to both working in production and locally :+1:
=> Fix consignment seq reference

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/DeferredResolver.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/test/resources/json/getconsignment_data_all.json, src/test/resources/json/getconsignment_query_alldata.json, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala
These changes retrieve a specified consignment's consignment reference from the DB and creates a service to call this method.
A `consignmentReference` field has been added to the consignment fields and the deferred resolver. This will allow us to add the `consignmentReference` to the generated [graphql query](https://github.com/nationalarchives/tdr-generated-graphql/blob/master/src/main/graphql/GetConsignmentSummary.graphql) for the transfer summary page.
=> Get consignment reference

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/DeferredResolver.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ClientFileMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/TransferAgreementRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
This PR changes the `consignmentReference` field on the API to be a normal field rather than utilising the deferred resolver. It has no effect on the [relevant generated graphql query](https://github.com/nationalarchives/tdr-generated-graphql/blob/master/src/main/graphql/GetConsignmentSummary.graphql#L10).
I also took the chance to fix some of the routeSpec tests as they were explicitly inserting into the test `Consignment` table rather than utilising available helper methods. I edited the existing helper method and changed tests to call this rather than hard-coding SQL. Though there was a test within the `ConsignmentRouteSpec` which was inserting more complex data that I left hard-coded.
=> Make consignment ref normal field

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestDatabase.scala
These changes update the newly created `ConsignmentStatus` table upon consignment upload, to facilitate showing the user an error should they try to upload for a consignment that already has an upload.
This is performed using the Slick `transactionally` combinator to perform the `File` table update as well as the `ConsignmentStatus` insert. This means that if anything goes wrong within the function both tables will not be updated, helping us keep our data consistent across tables. Within the `FileService` `addFile` function I've added functionality to insert the `ConsignmentStatusRow` with some info hard-coded for now, but we can change this once we're utilising the `ConsignmentStatus` table for other points in the user journey.
I've also added a test for the repository method and made …
=> Update consignment status upon upload

README.md
IntelliJ is confusing run config with test run config and causing issues when trying to run the API tests. These instructions should help other developers run tests for API code without coming across this error.
=> Add IntelliJ test run instructions to ensure devs can effectively run tests

src/main/resources/application.base.conf, src/main/resources/application.env-base.conf, src/main/resources/application.intg.conf, src/main/resources/application.prod.conf, src/main/resources/application.staging.conf
Add a new layer of config file which is the base for the hosted environments (intg, staging and prod). Move the database config into this file, so that the dev environment doesn't try to load the non-existent environment variables `DB_PORT` and `DB_ADDR`.
=> Only require database port and host in environment-specific config

src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
The getFileMetadata method was getting complicated because all the logic for getting the FFID and client side metadata was in a single method. If we were to add the antivirus to this then it would be too messy. I've refactored this so the client metadata and the FFID metadata comes from different methods.
=> Refactor file service getFileMetadata method

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/AntivirusMetadataRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
This adds the antivirus metadata to the consignment output. There is a new service method to get the data and a test for that.
=> Add antivirus metadata

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileStatusService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileStatusServiceSpec.scala
The logic originally only worked if there was only a single file for a
consignment. If there's more than one and any one has no status errors,
then it was returning allChecksSucceeded true.
I've changed this so it checks to make sure there are statuses and that
none of them are not Success. I've added a couple of tests to check for
this as well.
=> Fix the logic for allChecksSucceeded

build.sbt, src/main/resources/logback.xml, src/main/scala/uk/gov/nationalarchives/tdr/api/service/AntivirusMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/utils/LoggingUtils.scala
- Set logs to output in json format.
- Log the file status so we can query this in Grafana
=> Set json logs and output file status

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentService.scala, src/test/resources/scripts/init.sql, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
The ConsignmentSequence column on Consignment is now mandatory so I've
updated the library and removed all of the Option[Long]
There was also a change in the database library to add ModifiedDate to
ConsignmentStatus which I've added to the test init script.
=> Update db library

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/auth/AuthorisationTags.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/SeriesFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/model/TransferringBody.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/ConsignmentRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/SeriesServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/TransferringBodyServiceSpec.scala
This includes the change to drop the Code column from the Body table which will stop slick trying to select from it.
The new changes also include making some columns mandatory. To update to the latest version of the generated slick classes, I've removed all of the options from these fields.
=> Update generated graphql version

build.sbt, schema.graphql
The sbt-graphql graphqlValidateSchema plugin ignores any non-breaking changes. [The code doing this is here 
](https://github.com/muuki88/sbt-graphql/blob/37d62dd17475cadcea23cd0a000df8152b633189/src/main/scala/rocks/muki/graphql/GraphQLSchemaPlugin.scala#L166)
We would like this to fail on any schema changes, not just ones which will break so I've changed the graphqlValidateSchema task to do this. I've modified the code from the original plugin to do this.
I've also change the `schema.graphql` file. The changes to this should have failed on the PR that put didn't so I'm adding them in here so the build will pass.
=> Change the validateGraphqlSchema task to not ignore breaking changes.

Dockerfile
This reverts commit 3755203454727a0a3ccbeb9d7878e17f6a540c62.
It looks like this isn't actually needed, because the previous version didn't report any vulnerabilities in ECR.
=> Revert "Make sure we're using the latest version of apk-tools"

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FFIDMetadataRepository.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FFIDMetadataRepositorySpec.scala
There is potential that the ffid matches will not contain any results
In this case ensure that the file checks do not complete
=> Ensure only files with ffid matches are counted

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala, src/test/resources/json/addffidmetadata_data_no_ffid_matches.json, src/test/resources/json/addffidmetadata_mutation_no_ffid_matches.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FFIDMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataServiceSpec.scala
There is the potential that no ffid matches are returned
When this happens no ffid metadata should be added to prevent invalid data being stored in the database
=> Do not add ffid metadata if no ffid matches

src/main/scala/uk/gov/nationalarchives/tdr/api/http/ApiServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/Routes.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/CorsSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/RouteAuthenticationSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/RoutesSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FullHealthCheckServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestRequest.scala
What I think is happening is that DbConnection.db is being called when the API starts which is caching the current IAM password but then it's never being called again so we never get an updated passsword. I've removed it from the Routes constructor and added called it within the route definition.
I've moved the test which runs against the closed database out of the RouteAuthenticationSpec as it's not possible to do it in there now and added it into the FullHealthCheckServiceSpec class.
=> Move DbConnection.db from the Routes constructor.

Dockerfile
We have tried upgrading busybox on the openjdk image but it seems to be
on an older version of alpine and there are still vulnerabilities in the
latest version of busybox for that version.
Instead of using the openjdk image, I've changed this to use the
standard alpine image and installed openjdk 15 from the alpine edge
repository.
I've tested this on integration and it's working.
=> Use base alpine image with jdk 15 installed.

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServer.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileStatusService.scala, src/test/resources/json/addffidmetadata_data_fileid_not_exists.json, src/test/resources/json/addffidmetadata_mutation_status_judgment_format.json, src/test/resources/json/addffidmetadata_mutation_status_judgment_format_zip.json, src/test/resources/json/addffidmetadata_mutation_status_judgment_multiple_success.json, src/test/resources/json/addffidmetadata_mutation_status_judgment_password_protected_success.json, src/test/resources/json/addffidmetadata_mutation_status_judgment_zip_success.json, src/test/resources/json/addffidmetadata_mutation_status_non_judgment_format.json, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FFIDMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
To support court judgment transfers only a limited number of file formats are permissble to allow downstream processes to function
Limit court judgment files to permitted puids values
Make call to DB to determine whether file being checked belongs to a 'judgment' consignment, and apply appropriate test
=> Add check for judgment puid allow list

.github/workflows/build.yml
This was pointing to the branch when trying to run the deploy job which
no longer exists.
=> Remove temp branch code.

.github/workflows/build.yml
We're running sbt assembly here which needs the test container image so
it needs to be built first.
=> Build the test containers image.

.github/mergify.yml, .github/workflows/test.yml, .scala-steward.conf
I've signed this repo up to get the scala steward updates. We also want
these to be auto merged because we don't want more dependency updates to
worry about.
I've added in the mergify config and got scalastyle to ignore the
consignment-api-db changes as there's an ancient version in maven.
I've also change the test trigger from pull_request to
pull_request_target. This means that the code for the github actions
always comes from master but this is fine because there's a push trigger
as well which will catch any errors if we do make changes to the action
files.
=> Add mergify yaml and scala steward config.

.github/workflows/deploy.yml
The deploy job needs the contents write permission to be able to tag and
push the release branch. The calling job needs to have the same
permissions as the tdr-github-actions workflow.
=> Add write permission.

.github/workflows/deploy.yml
This is needed for the reusable workflow to assume the correct role in
the environment account.
=> Pass account number.

.github/mergify.yml
The name of the check is now test / test so needs to be updated to
allow mergify to work.
Needs https://github.com/nationalarchives/tdr-github-actions/pull/5
to be merged first.
=> Rename mergify check.

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
This should also reduce warning that appears when you run 'sbt graphqlSchemaGen'
=> Account for case that there is a 'Some' of something other than 'cfm'

Dockerfile
There is a vulnerability published for this library and this hasn't been
upgraded in the alpine repositories yet.
=> Upgrade libretls.

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/resources/json/addfileandmetadata_data_all.json, src/test/resources/json/addfileandmetadata_mutation_alldata.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
Originally, we were creating files and then assigning an arbitrary file
ID to add the metadata. This worked because there was nothing in the
file table which identified the file it came from.
We now have a file name but we're still arbitrarily assigning IDs to the
FileMetadata table so sometimes, the file name and the original path
don't match up.
I've updated this to create the file rows and the fileMetadata rows
together with each loop through the values from the generateNodes
method.
I've added a test to check that the file name and original path match
and updated a couple of other tests where this has broken them.
=> Fix mismatched file ids

.github/workflows/test.yml, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/resources/json/addfileandmetadata_data_all.json, src/test/resources/json/addfileandmetadata_mutation_alldata.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala
This line
`val pathWithoutSlash = if (m.originalPath.startsWith("/")) m.originalPath.tail else path`
seems to have been put in place in case we get a forward slash sent to the API.
The problem was that the originalPath sent from the front end has no leading slash so it was returning the calculated input `path` which we were then comparing with the calculated input `path` which always returned true.
We then called head on the list and got the same object each time.
This returned the same match id to the front end for both files so the front end uploaded the same file twice.
We have changed the tests so they match the real inputs. They have no leading slash.
We may not even need this check for the forward slash but we don't want to remove it now in case it handles an edge case somewhere.
=> Fix the file metadata matching.

.github/workflows/test.yml
This is now optional in tdr-github-actions. Once all the repos have removed it, we can take it out of that repo.
=> Remove MANAGEMENT_ACCOUNT

schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
In this query, it is populated with total files which is used on the
front end to display the total number of files for that folder.
I kept the name slightly more generic because this case class can be
used for other non-file things.
Instead of writing whole new tests I've added a couple of assertions
about the new totalItems field.
=> Add a total items field.

build.sbt, schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/CustomMetadataFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesServiceSpec.scala
This returns the ordinal value from the database where it's set. If it's not set, it returns `Int.MaxValue` This should make sure that any unordered fields show up at the end and simplifies the sorting on the client.
=> Add ordinal to metadata query

build.sbt
SLF4J needs to check the META-INF services directory to find the logging
implementation but it can't because the assembly plugin deletes it.
This keeps the services directory and now we have logging again.
=> Add a line to the merge strategy.

src/test/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesServiceSpec.scala
..To be aligned with recent db changes. There wasn't any instances of 'open_on_transfer' found in the api
=> Rename 'closed_for' to 'Closed'..

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
I was adding the ClientChecks status row to the ConsignmentStatus table
on startUpload and I was trying to add it again when the metadata was
complete.
This doesn't work as there should only be one ConsignmentStatus row so
I've called updateConsignmentStatus.
I've added a test to check for this.
=> Update ClientChecks status.

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
This is a temporary change so that the migrations don't break the existing form. There will be another pr to use only "DescriptionClosed" once the migrations are in.
=> Rename descriptionPublic to DescriptionClosed part 1

src/main/resources/application.base.conf, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/ValidationTag.scala
This is part of TDR-2509. Uploads with large numbers of files are timing
out but the database isn't running at capacity so we just need to wait a
bit longer for results.
I've tried these timeouts with 10000 files and it's working.
=> Increase some timeouts.

src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepository.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepositorySpec.scala
The underscore character is a wildcard character in postgres
https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP
The similar to is then looking for anything which ends with R.extension
instead of looking for something that ends in _R.extension. The
filenames which were failing all ended in R.
I've added another test to check for this which I think should cover it.
=> Fix for the redacted files.

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala
Cannot have a 'DescriptionAlternate' property without a 'description' property
'DescriptionAlternate' property is a dependency of 'DescriptionClosed' property
If 'description' is deleted then 'DescriptionClosed' property to be set back to default of 'false' and 'DescriptionAlternate' to be deleted
=> Ensure file metadata in correct state if 'description' deleted

src/main/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataServiceSpec.scala
Wait for metadata to be added.
`deleteFileStatus` and `addFileStatuses` were not flatMapped so sometimes they weren't completing before we were reading the file statuses to  determine the consignment statuses which lead to wrong results.
This adds these two methods into the for comprehension and this seems to be ok now.
I've also updated a couple of tests to mock out the calls to the methods.
=> Wait for metadata to be added

schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FileMetadataFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala
[TDR-3064](https://national-archives.atlassian.net/browse/TDR-3064?atlOrigin=eyJpIjoiMzE2OGUyODYzNGFmNDZjM2I4ZjBjNDJlNjgzN2RkMDkiLCJwIjoiaiJ9)
Ticket is to remove a depreciated method in such a way as to not impact other services. This method seems to only be referenced internally, and tests pass locally.
[TDR-3064]: https://national-archives.atlassian.net/browse/TDR-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TDR-3064 Remove Depreciated addFileMetaData Method

schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FFIDMetadataFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FFIDMetadataService.scala
[TDR-3063](https://national-archives.atlassian.net/browse/TDR-3063?atlOrigin=eyJpIjoiYzk3YzcyYmQ5ZGFmNDIxNGJhNDYwNDRmZjk0YWVkMGQiLCJwIjoiaiJ9)
Ticket is to remove a depreciated method in such a way as to not impact other services. This method seems to only be referenced internally, and tests pass locally.
[TDR-3063]: https://national-archives.atlassian.net/browse/TDR-3063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TDR-3063 Remove Depreciated FFIDMetaservice

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/resources/json/deletefilemetadata_data_error_no_consignmentid.json, src/test/resources/json/deletefilemetadata_data_error_not_file_owner.json, src/test/resources/json/deletefilemetadata_mutation_alldata.json, src/test/resources/json/deletefilemetadata_mutation_no_consignmentid.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala
Requires PR: https://github.com/nationalarchives/tdr-transfer-frontend/pull/3094
To remove the need to make an extra call to the DB use the consignment id arg passed into the mutation
=> Use consignment id arg instead of value from file

build.sbt
Akka newer versions of Akka causing an issue with route spec tests running on Github actions
Upgrading to the last working version as current running version of Akka has vulnerabilities
=> Update Akka to 10.5.0

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileService.scala, src/test/resources/json/getconsignment_data_all.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
FileReference and ParentReference needs to be inserted into the FileMetadata table in order to included in the export bagit.
=> Add fileReference and parentReference to fileMetadata

build.sbt, src/main/resources/application.base.conf, src/main/resources/application.conf, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/DisplayPropertiesRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServerBase.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/DisplayPropertiesService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/utils/MetadataValidationUtils.scala, src/test/resources/application.conf, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/DisplayPropertiesRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/DisplayPropertiesServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataServiceSpec.scala
Use metadata validation library to validate while updating/deleting additional metadata
Add a feature access block for the library
=> TDR-3414 - Use metadata validation library to validate metadata

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepository.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/FileMetadataFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/http/GraphQLServerBase.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileMetadataRepositorySpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala
Remove `MetadataId` & `Datetime` creation as these are generated automatically from the DB.
=> TDR-3536 Remove `metadataid` creation for FileMetadata table

src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
Refactored "static-metadata" properties to use string literals instead as defaults pulled from db
=> TDR-2207 Tidy up of metadata properties

lightbend.sbt
Scala Steward is failing because an exception was thrown if no akka token value
There is no way to pass the akka token into Scala Steward so providing a dummy value for the token instead of throwing the exception
=> Provide a dummy Akka token value as a default

src/main/scala/uk/gov/nationalarchives/tdr/api/metadatainputvalidation/MetadataInputTags.scala, src/test/resources/json/addorupdatebulkfilemetadata_data_error_not_file_owner.json, src/test/resources/json/deletefilemetadata_data_error_not_file_owner.json, src/test/resources/json/updatebulkfilemetadata_data_error_not_file_owner.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala
Draft metadata validator doesn't know the user id and due to this, the `addOrUpdateBulkFileMetadata` mutation throws an error that `User 'id' does not own the files they are trying to access`. So, for now, allow backend check client to access any consignment and files.
=> Allow backend check client to access any consignment and files

src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/ValidationTag.scala
As a follow-up to yesterday increase on `staging` of request-timeout  https://github.com/nationalarchives/tdr-consignment-api/pull/852 to understand where bottle neck is:
- that has stopped `request-timeout` error previously seen but we encounter a (new) 504 behind it. 
- think this `await result` will be source of that... mainly based on https://github.com/nationalarchives/tdr-consignment-api/commit/cd3aec131042fb145f3aadaa627000f5b8d66b15 where it was updated alongside the request-timeout in 2022 (and noted at that time that going to 2 mins worked with 10,000 files so testing to see if a little more time is all that is required).
=> TDRD-148: bump future time-out in validate

src/main/scala/uk/gov/nationalarchives/tdr/api/auth/AuthorisationTags.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentRouteSpec.scala
This allows TNAUsers to call the required api's such as downloading metadata or fetching consignment details
=> TDRD-336 - Give tna user permission to call consignment api's

schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/CustomMetadataFields.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/CustomMetadataPropertiesService.scala, src/main/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataService.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileMetadataRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/FileRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/FileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ValidateFileMetadataServiceSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/utils/TestUtils.scala
With Parliamentary Archives `LegalStatus` and `RightsCopyright` will be editable so we can use the existing `editable` property in the `FileProperty` table to get protected properties instead.
=> TDRD 217 Remove `PropertyProtected` and use `editable` instead

build.sbt, src/main/scala/uk/gov/nationalarchives/tdr/api/db/repository/FileRepository.scala
hopefully this will fix the slick upgrade. Quite a few changes including in pre-release
chore: drop usage of akka.dispatch.ExecutionContexts in https://github.com/akka/akka-http/pull/4422
=> update akkaHttpVersion as this is compatible with akkaVersion 2.10.0

schema.graphql, src/main/scala/uk/gov/nationalarchives/tdr/api/graphql/fields/ConsignmentStatusFields.scala, src/test/resources/json/updateconsignmentstatus_mutation_incorrect_override_user_id.json, src/test/resources/json/updateconsignmentstatus_mutation_override_user_id.json, src/test/scala/uk/gov/nationalarchives/tdr/api/routes/ConsignmentStatusRouteSpec.scala, src/test/scala/uk/gov/nationalarchives/tdr/api/service/ConsignmentStatusServiceSpec.scala
To support SharePoint and other third party service transfers the updating of Consignment statuses will be done via a service client user
The user id in the bearer access token will be the service client user and not the user that owns the transfer this will cause an Authorisation Exception
These changes will allow the service client user to update Consignment statuses for all consignments
=> Sptdr service transfer status update permissions

src/main/scala/uk/gov/nationalarchives/tdr/api/auth/AuthorisationTags.scala
To ensure the continuing integrity of the user id ovveride check use separate transfer service client role for providing general access to a consignment
Transfer service client needs access to consignment data to support SharePoint transfer features
=> New transfer service role to give access permission to consignment
